// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: menglei/test.proto
package protoGen.menglei;

import android.os.Parcelable;
import android.support.annotation.Nullable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import okio.ByteString;

public final class Test2 extends AndroidMessage<Test2, Test2.Builder> {
  public static final ProtoAdapter<Test2> ADAPTER = ProtoAdapter.newMessageAdapter(Test2.class);

  public static final Parcelable.Creator<Test2> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NAME2 = "";

  public static final Integer DEFAULT_COUNT2 = 0;

  public static final Double DEFAULT_MASS_KILOGRAMS2 = 0.0d;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  @Nullable
  public final String name2;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REPEATED
  )
  public final List<String> picture_urls2;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  @Nullable
  public final Integer count2;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#DOUBLE"
  )
  @Nullable
  public final Double mass_kilograms2;

  public Test2(@Nullable String name2, List<String> picture_urls2, @Nullable Integer count2,
      @Nullable Double mass_kilograms2) {
    this(name2, picture_urls2, count2, mass_kilograms2, ByteString.EMPTY);
  }

  public Test2(@Nullable String name2, List<String> picture_urls2, @Nullable Integer count2,
      @Nullable Double mass_kilograms2, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.name2 = name2;
    this.picture_urls2 = Internal.immutableCopyOf("picture_urls2", picture_urls2);
    this.count2 = count2;
    this.mass_kilograms2 = mass_kilograms2;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.name2 = name2;
    builder.picture_urls2 = Internal.copyOf("picture_urls2", picture_urls2);
    builder.count2 = count2;
    builder.mass_kilograms2 = mass_kilograms2;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Test2)) return false;
    Test2 o = (Test2) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(name2, o.name2)
        && picture_urls2.equals(o.picture_urls2)
        && Internal.equals(count2, o.count2)
        && Internal.equals(mass_kilograms2, o.mass_kilograms2);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (name2 != null ? name2.hashCode() : 0);
      result = result * 37 + picture_urls2.hashCode();
      result = result * 37 + (count2 != null ? count2.hashCode() : 0);
      result = result * 37 + (mass_kilograms2 != null ? mass_kilograms2.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Test2, Builder> {
    public String name2;

    public List<String> picture_urls2;

    public Integer count2;

    public Double mass_kilograms2;

    public Builder() {
      picture_urls2 = Internal.newMutableList();
    }

    public Builder name2(String name2) {
      this.name2 = name2;
      return this;
    }

    public Builder picture_urls2(List<String> picture_urls2) {
      Internal.checkElementsNotNull(picture_urls2);
      this.picture_urls2 = picture_urls2;
      return this;
    }

    public Builder count2(Integer count2) {
      this.count2 = count2;
      return this;
    }

    public Builder mass_kilograms2(Double mass_kilograms2) {
      this.mass_kilograms2 = mass_kilograms2;
      return this;
    }

    @Override
    public Test2 build() {
      return new Test2(name2, picture_urls2, count2, mass_kilograms2, super.buildUnknownFields());
    }
  }
}
