// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: menglei/protos.proto
package protoGen.menglei;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import okio.ByteString;

public final class role_pay_req extends Message<role_pay_req, role_pay_req.Builder> {
  public static final ProtoAdapter<role_pay_req> ADAPTER = ProtoAdapter.newMessageAdapter(role_pay_req.class);

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_VALUE = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer value;

  public role_pay_req(Integer value) {
    this(value, ByteString.EMPTY);
  }

  public role_pay_req(Integer value, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.value = value;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.value = value;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof role_pay_req)) return false;
    role_pay_req o = (role_pay_req) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(value, o.value);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (value != null ? value.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<role_pay_req, Builder> {
    public Integer value;

    public Builder() {
    }

    public Builder value(Integer value) {
      this.value = value;
      return this;
    }

    @Override
    public role_pay_req build() {
      return new role_pay_req(value, super.buildUnknownFields());
    }
  }
}
